import { test, expect } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import { emptyProject, captureProject, restoreProject } from "../../src/lib/project/workspace";
import { useEditorStore } from "../../src/store/editorStore";
import { templates } from "../../src/templates";
import { defaultAnimation, neutralFrame, stackAnimations } from "../../src/lib/animation";
import { generateAnimationSetup } from "../../src/lib/codegen/animationCodegen";

test("animation tab edits stacked keyframes, scrubs the canvas, persists, and runs in generated preview", async ({ page }) => {
    restoreProject(emptyProject("Animation studio"));
    const store = useEditorStore.getState();
    store.updateCanvasSettings({ width: 1280, height: 2200 });
    const id = store.addElement({ ...templates.shape, label: "Motion object", styles: { ...templates.shape.styles, backgroundColor: "#ad91ff", borderRadius: "16px" }, layout: { w: 180, h: 180, opacity: 0.5 } }, undefined, 280, 250);
    const group = store.addElement({ ...templates.container, label: "Stagger group", animation: { ...defaultAnimation(), name: "Child sequence", duration: 1, target: "children", stagger: 2 } }, undefined, 650, 250);
    const children = [0, 1].map(index => store.addElement({ ...templates.shape, layout: { w: 60, h: 60, opacity: 0.6 }, styles: { ...templates.shape.styles, backgroundColor: "#ad91ff" } }, group, index * 80, 0));
    const project = captureProject("animations-test", "Animation studio");
    await page.goto("/");
    await page.getByLabel("Import project backup", { exact: true }).setInputFiles({ name: "animations.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(project)) });
    const link = page.getByRole("link", { name: "Open Animation studio (import)", exact: true });
    await expect(link).toBeVisible();
    const href = await link.getAttribute("href");
    await page.goto(href!);
    await expect(page.getByRole("button", { name: "Save project", exact: true })).toBeEnabled();
    const object = page.locator(`.canvas-page [data-element-id="${id}"]`);
    await object.click();
    await page.getByRole("button", { name: "Animate", exact: true }).click();
    const panel = page.getByRole("region", { name: "Animation editor" });
    await panel.getByRole("button", { name: "Cinematic reveal", exact: true }).click();
    await panel.getByLabel("Effect name", { exact: true }).fill("Product entrance");
    await panel.getByLabel("Effect name", { exact: true }).press("Tab");
    await panel.getByRole("button", { name: "Select keyframe at 100%", exact: true }).click();
    await panel.getByLabel("Keyframe Move X", { exact: true }).fill("120");
    await panel.getByLabel("Keyframe Move X", { exact: true }).press("Tab");
    await panel.getByRole("button", { name: "Add keyframe", exact: true }).click();
    await expect(panel.getByRole("button", { name: "Select keyframe at 50%", exact: true })).toBeVisible();
    await panel.getByLabel("Keyframe Move X", { exact: true }).fill("80");
    await panel.getByLabel("Keyframe Move X", { exact: true }).press("Tab");
    await panel.getByLabel("Animation preview progress", { exact: true }).fill("50");
    expect(await object.evaluate(node => node.getAnimations().length)).toBeGreaterThan(0);
    await panel.getByRole("button", { name: "Reset effect preview", exact: true }).click();
    await panel.getByRole("button", { name: "Add effect", exact: true }).click();
    await panel.getByRole("button", { name: "Hover", exact: true }).click();
    await panel.getByLabel("Effect name", { exact: true }).fill("Interactive lift");
    await panel.getByLabel("Effect name", { exact: true }).press("Tab");
    await expect(panel.getByLabel("Hover leave behavior", { exact: true })).toHaveValue("reverse");
    await panel.getByRole("button", { name: "Add effect", exact: true }).click();
    await panel.getByRole("button", { name: "Scroll", exact: true }).click();
    await panel.getByRole("button", { name: "Scrub with scroll", exact: true }).click();
    await panel.getByLabel("Effect name", { exact: true }).fill("Scroll depth");
    await panel.getByLabel("Effect name", { exact: true }).press("Tab");
    await expect(panel.getByLabel("Scroll start", { exact: true })).toHaveValue("80");
    await mkdir(".verification/animations", { recursive: true });
    await page.screenshot({ path: ".verification/animations/desktop.png" });
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.screenshot({ path: ".verification/animations/compact.png" });
    expect(await panel.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
    await page.setViewportSize({ width: 1600, height: 1000 });
    await panel.getByLabel("Keyframe Move X", { exact: true }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: ".verification/animations/keyframes-desktop.png" });
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.screenshot({ path: ".verification/animations/keyframes-compact.png" });
    await page.setViewportSize({ width: 1600, height: 1000 });
    await page.getByRole("button", { name: "Save project", exact: true }).click();
    await page.reload();
    await page.getByRole("button", { name: "Layers", exact: true }).click();
    await page.getByRole("treeitem", { name: "Motion object", exact: true }).click();
    await page.getByRole("button", { name: "Animate", exact: true }).click();
    await expect(panel).toContainText("3 / 8 effects");
    await expect(panel).toContainText("Product entrance");
    await expect(panel).toContainText("Interactive lift");
    await expect(panel).toContainText("Scroll depth");
    await panel.getByRole("button", { name: /Product entrance.*Page load/ }).click();
    await panel.getByLabel("Animation direction", { exact: true }).selectOption("reverse");
    await panel.getByRole("button", { name: "Open page motion timeline", exact: true }).click();
    await expect(page.locator(".motion-tracks > button")).toHaveCount(2);
    const motionPanel = page.getByRole("region", { name: "Motion timeline", exact: true });
    await expect(motionPanel.getByLabel("Delete keyframe 1", { exact: true })).toBeDisabled();
    await expect(motionPanel.getByLabel("Delete keyframe 3", { exact: true })).toBeDisabled();
    await motionPanel.getByLabel("Keyframe 3 x", { exact: true }).fill("160");
    await motionPanel.getByLabel("Keyframe 3 x", { exact: true }).press("Tab");
    await motionPanel.getByLabel("Animation playhead", { exact: true }).fill("0");
    expect(await object.evaluate(node => Math.round(new DOMMatrix(getComputedStyle(node).transform).m41))).toBe(160);
    await expect(object).toHaveCSS("opacity", "0.5");
    await expect(motionPanel.getByLabel("Animation playhead", { exact: true })).toHaveAttribute("max", "3");
    await motionPanel.getByLabel("Animation playhead", { exact: true }).fill("3");
    for (const child of children) await expect(page.locator(`.canvas-page [data-element-id="${child}"]`)).toHaveCSS("opacity", "0.6");
    await page.getByRole("button", { name: "Close motion timeline", exact: true }).click();
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.getByRole("button", { name: "Preview", exact: true }).click();
    const frame = page.frameLocator('iframe[title="Generated frontend preview"]');
    await expect(frame.locator(`.el-${id}`)).toBeVisible();
    await expect.poll(() => frame.locator(`.el-${id}`).evaluate(node => node.getAnimations().length)).toBeGreaterThan(0);
    expect(errors).toEqual([]);
});

test("generated motion composes hover transforms, reverses, scrubs both ways, handles pointer and reduced motion", async ({ page }) => {
    const load = { ...defaultAnimation(), duration: 0.05, keyframes: [{ ...neutralFrame }, { ...neutralFrame, time: 1, x: 30 }] };
    const hover = { ...defaultAnimation("custom", "onHover"), duration: 0.12, easing: "linear", keyframes: [{ ...neutralFrame }, { ...neutralFrame, time: 1, y: -40 }] };
    const scroll = { ...defaultAnimation("custom", "onScroll"), scrollMode: "scrub" as const, easing: "linear", keyframes: [{ ...neutralFrame, x: -100 }, { ...neutralFrame, time: 1, x: 100 }] };
    const pointer = { ...defaultAnimation("tilt3D", "onPointerMove"), pointerMode: "follow" as const, intensity: 20 };
    const stagger = { ...defaultAnimation(), duration: 0.1, target: "children" as const, stagger: 0.3 };
    const reveal = { ...defaultAnimation("custom", "onScroll"), duration: 0.1, scrollOffset: 20, scrollReplay: true };
    await page.setContent('<style>body{margin:0;height:3500px}.box{position:absolute;left:200px;width:120px;height:100px;background:#ad91ff}#hover{top:100px;transform:rotate(20deg)}#scroll{top:1200px}#pointer{top:260px}#children{top:400px}#children span{display:inline-block;width:20px;height:20px;background:red}</style><button class="box" id="hover">Hover</button><div class="box" id="scroll"></div><div class="box" id="pointer"></div><div class="box" id="children"><span>A</span><span>B</span></div>');
    const config = [{ className: "hover", anim: stackAnimations([load, hover])! }, { className: "scroll", anim: scroll }, { className: "pointer", anim: pointer }, { className: "children", anim: stagger }];
    await page.locator(".box").evaluateAll(nodes => nodes.forEach(node => node.classList.add(node.id)));
    await page.evaluate(() => {
        const node = document.createElement("div"); node.className = "reveal";
        Object.assign(node.style, { position: "absolute", top: "990px", height: "100px", width: "100px" });
        document.body.appendChild(node);
    });
    config.push({ className: "reveal", anim: reveal });
    await page.addScriptTag({ content: generateAnimationSetup(config) + "; window.disposeMotion = setupAnimations(document);" });
    await expect.poll(() => page.locator(".reveal").evaluate(node => node.getAnimations().length)).toBe(0);
    await page.evaluate(() => window.scrollTo(0, 30));
    await expect.poll(() => page.locator(".reveal").evaluate(node => node.getAnimations().length)).toBeGreaterThan(0);
    await page.evaluate(() => window.scrollTo(0, 0));
    await expect.poll(() => page.locator(".reveal").evaluate(node => node.getAnimations().length)).toBe(0);
    const hoverElement = page.locator("#hover");
    await expect.poll(() => hoverElement.evaluate(node => node.getAnimations().length)).toBe(1);
    await page.locator("#children span").evaluateAll(nodes => nodes.forEach(node => node.getAnimations().forEach(player => { player.pause(); player.currentTime = 150; })));
    await expect(page.locator("#children span").nth(0)).toHaveCSS("opacity", "1");
    expect(await page.locator("#children span").nth(1).evaluate(node => Number(getComputedStyle(node).opacity))).toBeLessThan(1);
    await page.locator("#children span").evaluateAll(nodes => nodes.forEach(node => node.getAnimations().forEach(player => { player.currentTime = 400; })));
    await expect.poll(() => page.locator("#children span").nth(1).evaluate(node => Number(getComputedStyle(node).opacity))).toBe(1);
    const base = await hoverElement.evaluate(node => getComputedStyle(node).transform);
    await hoverElement.hover();
    await expect.poll(() => hoverElement.evaluate(node => Math.round(new DOMMatrix(getComputedStyle(node).transform).m42))).toBe(-27);
    expect(await hoverElement.evaluate(node => getComputedStyle(node).transform)).not.toBe(base);
    await page.mouse.move(20, 20);
    await expect.poll(() => hoverElement.evaluate(node => getComputedStyle(node).transform)).toBe(base);
    await hoverElement.focus();
    await expect.poll(() => hoverElement.evaluate(node => Math.round(new DOMMatrix(getComputedStyle(node).transform).m42))).toBe(-27);
    await hoverElement.evaluate(node => (node as HTMLElement).blur());
    await expect.poll(() => hoverElement.evaluate(node => getComputedStyle(node).transform)).toBe(base);
    const offset = () => page.locator("#scroll").evaluate(node => new DOMMatrix(getComputedStyle(node).transform).m41);
    await expect.poll(offset).toBe(-100);
    await page.evaluate(() => window.scrollTo(0, 1100));
    await expect.poll(offset).toBe(100);
    await page.evaluate(() => window.scrollTo(0, 700));
    await expect.poll(async () => Math.round(await offset())).toBe(-14);
    await page.evaluate(() => window.scrollTo(0, 0));
    await expect.poll(offset).toBe(-100);
    await page.mouse.move(300, 300);
    await expect.poll(() => page.locator("#pointer").evaluate(node => node.getAnimations().length)).toBe(1);
    await page.mouse.move(20, 20);
    await expect.poll(() => page.locator("#pointer").evaluate(node => node.getAnimations().length)).toBe(0);
    await page.emulateMedia({ reducedMotion: "reduce" });
    await expect.poll(() => page.locator(".box").evaluateAll(nodes => nodes.reduce((count, node) => count + node.getAnimations({ subtree: true }).length, 0))).toBe(0);
    await expect(page.locator("#scroll")).toHaveCSS("opacity", "1");
    await page.emulateMedia({ reducedMotion: "no-preference" });
    await expect.poll(() => page.locator("#scroll").evaluate(node => node.getAnimations().length)).toBeGreaterThan(0);
    await page.evaluate(() => (window as unknown as { disposeMotion: () => void }).disposeMotion());
    await hoverElement.hover();
    expect(await hoverElement.evaluate(node => node.getAnimations().length)).toBe(0);
});
