import { test, expect } from "@playwright/test";
import JSZip from "jszip";
import { readFile } from "node:fs/promises";
import { openEditor } from "../helpers/open-editor";
import { mappedLoginFixture } from "../helpers/mapped-login-fixture";

test("endpoint header contracts are editable, mapped by identity, saved and downloaded", async ({ page }) => {
  const { project, endpointId } = mappedLoginFixture(true);
  const corsBlock=project.backend.services[0].blocks.find(b=>b.type==="middleware" && b.config.middlewareType==="cors")!;
  corsBlock.label="CORS";
  await openEditor(page);
  await page.getByRole("button", { name: "Untitled project", exact: true }).click();
  const workspace = page.getByRole("dialog", { name: "Levoks project workspace" });
  await workspace.locator('input[type="file"]').setInputFiles({ name: "headers.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(project)) });
  await expect(workspace.getByLabel("Project name", { exact: true })).toHaveValue("Login workflow (import)");
  await workspace.getByRole("button", { name: "Close workspace" }).click();
  await page.getByRole("button", { name: "Backend", exact: true }).click();
  await page.locator(".backend-hierarchy .bh-block-name").getByText("CORS", { exact: true }).click();
  const cors = page.locator(".backend-inspector");
  await cors.getByLabel("Origins", {exact:true}).fill("*");
  await expect(cors.getByRole("alert")).toContainText("explicit HTTP(S) origins");
  await cors.getByLabel("Origins", {exact:true}).fill("https://client.example.test");
  await cors.getByLabel("CORS DELETE", {exact:true}).uncheck();
  await cors.getByLabel("Use automatic request headers", {exact:true}).uncheck();
  await cors.getByLabel("Allowed headers", {exact:true}).pressSequentially("Content-Type, X-App-Version");
  await cors.getByLabel("Allowed headers", {exact:true}).press("Tab");
  await expect(cors.getByLabel("Allowed headers", {exact:true})).toHaveValue("Content-Type, X-App-Version");
  await cors.getByLabel("Exposed headers", {exact:true}).fill("X-App-Result");
  await cors.getByLabel("Exposed headers", {exact:true}).press("Tab");
  await cors.getByLabel("Allow browser credentials", {exact:true}).uncheck();
  await cors.getByLabel("Preflight cache (seconds)", {exact:true}).fill("300");
  await page.screenshot({path:".verification/cors-desktop.png"});
  await page.setViewportSize({width:1024,height:768});
  await page.screenshot({path:".verification/cors-compact.png"});
  await page.setViewportSize({width:1600,height:1000});
  await page.locator(".backend-hierarchy .bh-block-name").getByText("Login", { exact: true }).click();
  const inspector = page.locator(".backend-inspector");
  await inspector.getByRole("button", { name: "Request Headers" }).click();
  const field = inspector.getByLabel("Field 1 name", { exact: true });
  await field.fill("Authorization");
  await expect(inspector.getByRole("alert")).toContainText("managed by the browser");
  await field.fill("X-App-Version");
  await expect(inspector.getByRole("alert")).toHaveCount(0);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(field).toHaveValue("Authorization");
  await page.getByRole("button", { name: "Redo", exact: true }).click();
  await expect(field).toHaveValue("X-App-Version");
  await page.locator(".backend-hierarchy .bh-block-name").getByText("Login response", {exact:true}).click();
  const responseName = inspector.getByLabel("Response header 1 name", {exact:true});
  const responseValue = inspector.getByLabel("Response header 1 value", {exact:true});
  await responseName.fill("Set-Cookie");
  await expect(inspector.getByRole("alert")).toContainText("managed by the browser");
  await responseName.fill("");
  await expect(inspector.getByRole("alert")).toContainText("must use letters");
  await responseName.fill("X-App-Result");
  await responseValue.fill("$result.");
  await expect(inspector.getByRole("alert")).toContainText("safe $context.path");
  await responseValue.fill("$result.email");
  await expect(inspector.getByRole("alert")).toHaveCount(0);
  await inspector.getByRole("button", {name:"Add response header",exact:true}).click();
  await inspector.getByLabel("Response header 2 name", {exact:true}).fill("X-App-Version");
  await inspector.getByLabel("Response header 2 value type", {exact:true}).selectOption("number");
  await inspector.getByLabel("Response header 2 value", {exact:true}).fill("7");
  await page.getByRole("button", {name:"Undo",exact:true}).click();
  await expect(inspector.getByLabel("Response header 2 value", {exact:true})).toHaveValue("0");
  await page.getByRole("button", {name:"Redo",exact:true}).click();
  await expect(inspector.getByLabel("Response header 2 value", {exact:true})).toHaveValue("7");
  await page.screenshot({path:".verification/response-headers-desktop.png"});
  await page.setViewportSize({width:1024,height:768});
  await page.screenshot({path:".verification/response-headers-compact.png"});
  await page.setViewportSize({width:1600,height:1000});
  await page.getByRole("button", { name: "Routes", exact: true }).click();
  const wire = page.getByRole("button", { name: "Select connection login_wire", exact: true });
  await wire.focus(); await wire.press("Enter");
  await expect(page.getByLabel("Source for header.X-App-Version")).toHaveValue("literal");
  await page.screenshot({ path: ".verification/header-mapping-desktop.png" });
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  await page.reload();
  await page.getByRole("button", { name: "Routes", exact: true }).click();
  await wire.focus(); await wire.press("Enter");
  await expect(page.getByLabel("Source for header.X-App-Version")).toHaveValue("literal");
  await page.getByRole("button", { name: "Deploy", exact: true }).click();
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download full-stack ZIP", exact: true }).click();
  const download = await downloadPromise;
  await download.saveAs(".verification/headers-export.zip");
  const zip = await JSZip.loadAsync(await readFile(".verification/headers-export.zip"));
  const saved = JSON.parse(await zip.file("levoks.ir.json")!.async("string"));
  const endpoint = saved.backend.services[0].blocks.find((b: {id: string}) => b.id === endpointId);
  expect(endpoint.config.requestHeaders[0]).toMatchObject({ id: "client_version", name: "X-App-Version", type: "number", required: true });
  expect(saved.backend.services[0].blocks.find((b:{type:string}) => b.type === "response").config.headers).toEqual([{name:"X-App-Result",value:"$result.email"},{name:"X-App-Version",value:7}]);
  expect(await zip.file("backend/auth-service/routes/index.js")!.async("string")).toContain("res.set(output.headers)");
  expect(saved.backend.services[0].blocks.find((b:{id:string})=>b.id===corsBlock.id).config).toMatchObject({corsOrigins:"https://client.example.test",corsAllowedHeaders:["Content-Type","X-App-Version"],corsExposedHeaders:["X-App-Result"],corsCredentials:false,corsMaxAge:300});
  expect(await zip.file("backend/auth-service/middleware/cors.js")!.async("string")).toContain('"credentials":false');
  expect(await zip.file("frontend/app/page.jsx")!.async("string")).toContain('"location":"header"');
  expect(await zip.file("frontend/app/%5F%5Flevoks/api/[service]/[...path]/route.js")!.async("string")).toContain('"x-app-version"');
});
