// ═══════════════════════════════════════════════════
// Code Generation — Express.js Templates
// ═══════════════════════════════════════════════════

import { serviceSlug } from "@/lib/project/schema";

export const PACKAGE_JSON_TEMPLATE = (name: string, port: number) => `{
  "name": "${serviceSlug(name)}",
  "version": "1.0.0",
  "description": "Generated by Levoks Backend Builder",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "dev": "nodemon server.js"
  },
  "dependencies": {
    "express": "^4.18.2",
    "mongoose": "^7.6.0",
    "cors": "^2.8.5",
    "dotenv": "^16.3.1",
    "helmet": "^7.1.0",
    "morgan": "^1.10.0",
    "bcryptjs": "^2.4.3",
    "jsonwebtoken": "^9.0.2",
    "express-rate-limit": "^7.1.4",
    "express-validator": "^7.0.1"
  },
  "devDependencies": {
    "nodemon": "^3.0.2"
  },
  "overrides": { "qs": "^6.16.0" },
  "engines": { "node": ">=22" }
}`;

export const SERVER_TEMPLATE = (port: number, imports: string, middlewareSetup: string, routeSetup: string, corsOrigins = "http://localhost:3000") => `
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || ${port};
const health = require('./observability/health');
health.mount(app);

// ─── Built-in Middleware ───
app.disable('x-powered-by');
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: false, limit: '1mb' }));
const allowedOrigins = (process.env.CORS_ORIGINS || ${JSON.stringify(corsOrigins)}).split(',').map(origin => origin.trim());
app.use(cors({ origin: allowedOrigins, credentials: true }));
app.use((req, res, next) => { if (!['GET', 'HEAD', 'OPTIONS'].includes(req.method) && req.headers.origin && !allowedOrigins.includes(req.headers.origin)) return res.status(403).json({ error: 'Origin not allowed' }); next(); });
app.use(helmet());
app.use(morgan('dev'));
app.use(require('express-rate-limit')({ windowMs: 60000, limit: 120, standardHeaders: true, legacyHeaders: false }));

${middlewareSetup}

${imports}

// ─── Routes ───
${routeSetup}

// ─── Error Handler ───
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(err.status || 500).json({
    error: {
      message: process.env.NODE_ENV === 'production' ? 'Request failed' : (err.message || 'Internal Server Error'),
      ...(process.env.NODE_ENV === 'development' && { stack: err.stack }),
    },
  });
});

// ─── Database Connection & Start ───
const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/${port === 3001 ? 'auth_db' : 'app_db'}';

mongoose.connect(MONGO_URI)
  .then(() => {
    console.log('✅ Connected to MongoDB');
    const server = app.listen(PORT, () => {
      console.log(\`🚀 Server running on port \${PORT}\`);
    });
    const shutdown = () => { health.drain(); server.close(() => { mongoose.disconnect().finally(() => process.exit(0)); }); setTimeout(() => process.exit(1), 10000).unref(); };
    process.once('SIGTERM', shutdown);
    process.once('SIGINT', shutdown);
  })
  .catch((err) => {
    console.error('❌ MongoDB connection error:', err);
    process.exit(1);
  });

module.exports = app;
`.trim();

export const MODEL_TEMPLATE = (modelName: string, fields: string) => `
const mongoose = require('mongoose');

const ${modelName}Schema = new mongoose.Schema({
${fields}
}, {
  timestamps: true,
});

module.exports = mongoose.model('${modelName}', ${modelName}Schema);
`.trim();

export const ROUTE_TEMPLATE = (routeName: string, endpoints: string) => `
const express = require('express');
const router = express.Router();

${endpoints}

module.exports = router;
`.trim();

export const AUTH_MIDDLEWARE_TEMPLATE = (identitySession = false, identityOrigin?: string, introspectionPath = "/api/auth/introspect", accessCookie = "levoks_session") => `
const jwt = require('jsonwebtoken');
${identitySession ? "const sessions = require('../identity/sessions');" : ""}

const auth = async (req, res, next) => {
  try {
    const bearer = req.header('Authorization')?.replace('Bearer ', '');
    const cookieName = ${JSON.stringify(accessCookie)};
    const cookie = req.headers.cookie?.split(';').map(value => value.trim()).find(value => value.startsWith(cookieName + '='))?.slice(cookieName.length + 1);
    if (!bearer && cookie && !['GET', 'HEAD'].includes(req.method) && !(process.env.CORS_ORIGINS || 'http://localhost:3000').split(',').includes(req.headers.origin)) return res.status(403).json({ error: 'Origin not allowed' });
    const token = bearer || (cookie ? decodeURIComponent(cookie) : '');
    if (!token) {
      return res.set('X-Levoks-Session', 'invalid').status(401).json({ error: 'Access denied. No token provided.' });
    }

    if (!process.env.JWT_SECRET || process.env.JWT_SECRET.length < 32) return res.status(503).json({ error: 'Authentication is not configured' });
    const decoded = jwt.verify(token, process.env.JWT_SECRET, { algorithms: ['HS256'] });
    ${identityOrigin ? `let response;
    try { response = await fetch((process.env.AUTH_IDENTITY_ORIGIN || ${JSON.stringify(identityOrigin)}).replace(/\\/$/, '') + ${JSON.stringify(introspectionPath)}, {method: 'POST', redirect: 'error', signal: AbortSignal.timeout(5000), headers: {Authorization: 'Bearer ' + token}}); }
    catch { return res.status(503).json({error: 'Identity service unavailable'}); }
    if (!response.ok) return res.set('X-Levoks-Session', [401, 403].includes(response.status) ? 'invalid' : 'unavailable').status([401, 403].includes(response.status) ? 401 : 503).json({error: 'Identity session unavailable or revoked'});
    const data = await response.json();
    if (typeof data.sub !== 'string' || data.sub !== decoded.sub || typeof data.sid !== 'string' || data.sid !== decoded.sid || typeof data.role !== 'string' || (data.tenantId !== undefined && typeof data.tenantId !== 'string')) return res.status(401).json({error: 'Invalid identity response'});
    req.user = {sub: data.sub, sid: data.sid, role: data.role, ...(data.tenantId ? {tenantId: data.tenantId} : {})};` : `req.user = ${identitySession ? "await sessions.verify(decoded)" : "decoded"};`}
    next();
  } catch (error) {
    res.set('X-Levoks-Session', 'invalid').status(401).json({ error: 'Invalid token.' });
  }
};

module.exports = auth;
`.trim();

export const CONTROLLER_TEMPLATE = (modelName: string, routes: string) => `
const ${modelName} = require('../models/${modelName}');

${routes}
`.trim();

export const ENV_TEMPLATE = (vars: Record<string, string>) => {
  return Object.entries(vars)
    .map(([key, value]) => `${key}=${value}`)
    .join('\n');
};

export const DOCKERFILE_TEMPLATE = (port: number) => `
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --package-lock-only --ignore-scripts && npm ci --omit=dev

COPY . .
ENV NODE_ENV=production
USER node

EXPOSE ${port}

CMD ["node", "server.js"]
`.trim();

export const DOCKER_COMPOSE_TEMPLATE = (services: { name: string; port: number; identityOrigin?: string }[]) => `
version: '3.8'

services:
  mongodb:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: app_db

${services.map(s => `  ${serviceSlug(s.name)}:
    build: ./${serviceSlug(s.name)}
    ports:
      - "${s.port}:${s.port}"
    environment:
      - PORT=${s.port}
      - JWT_SECRET=\${JWT_SECRET:-}
${s.identityOrigin ? `      - AUTH_IDENTITY_ORIGIN=${s.identityOrigin}\n` : ""}      - CORS_ORIGINS=\${CORS_ORIGINS:-http://localhost:3000}
      - MONGO_URI=mongodb://mongodb:27017/${serviceSlug(s.name).replace(/-/g, '_')}_db
    depends_on:
      - mongodb
    restart: unless-stopped`).join('\n\n')}

volumes:
  mongo-data:
`.trim();

export const README_TEMPLATE = (projectName: string, services: { name: string; port: number; description: string }[]) => `
# ${projectName}

> Generated by Levoks Backend Builder

## Services

${services.map(s => `### ${s.name}
- **Port**: ${s.port}
- **Description**: ${s.description || 'No description'}
`).join('\n')}

## Getting Started

### Prerequisites
- Node.js 22+
- MongoDB

### Installation

\`\`\`bash
npm install
\`\`\`

### Development

\`\`\`bash
npm run dev
\`\`\`

### Docker

\`\`\`bash
docker-compose up -d
\`\`\`

## API Documentation

Health check: \`GET /health\`
`.trim();
