"use client";
import { useState } from "react";
import { useEditorStore } from "@/store/editorStore";
import { templates } from "@/templates";
import { ICON_PATHS } from "@/lib/icon-paths";
import AssetUpload from "../AssetUpload";
export default function AssetLibrary() {
  const store = useEditorStore(), [query, setQuery] = useState("");
  const entries = Object.entries(store.assets).filter(([, asset]) => asset.name.toLowerCase().includes(query.toLowerCase()));
  return <div className="design-library-body asset-library"><AssetUpload /><label>Find an asset<input aria-label="Find an asset" value={query} onChange={event => setQuery(event.target.value)} placeholder="Images, fonts or icons" /></label><p>Assets are saved with this project and included in its backup and export. The project limit is 5 MB.</p>
    {entries.map(([id, asset]) => <div className="asset-library-item" key={id}>{asset.mime.startsWith("image/") ? <img src={asset.source} alt="" /> : <span style={{ fontFamily: `"LevoksFont-${id}", sans-serif` }}>Aa</span>}<div><strong>{asset.name}</strong><small>{asset.mime}</small><div className="design-button-row"><button disabled={asset.mime.startsWith("font/") && !store.selectedElementIds.length} onClick={() => { if (asset.mime.startsWith("image/")) store.addElement({ ...templates.image, label: asset.name, props: { src: "", assetId: id, alt: asset.name.replace(/\.[^.]+$/, "") }, layout: { w: Math.min(600, asset.width || 300), h: Math.max(20, Math.min(600, asset.width || 300) * (asset.height || 200) / (asset.width || 300)) } }); else { store.beginInteraction(); store.selectedElementIds.forEach(element => store.updateElement(element, { styles: { fontFamily: `"LevoksFont-${id}", sans-serif` } })); store.endInteraction(); } }}>{asset.mime.startsWith("image/") ? "Insert image" : "Apply font"}</button><button disabled={asset.mime.startsWith("font/") && [...Object.values(store.elementsById), ...Object.values(store.components).flatMap(definition => Object.values(definition.nodes))].some(node => JSON.stringify([node.styles, node.responsive]).includes(`LevoksFont-${id}`))} title="Images already placed keep their content; fonts in use must be replaced first" aria-label={`Remove asset ${asset.name}`} onClick={() => store.setAsset(id, null)}>Remove</button></div></div></div>)}
    {Object.values(store.elementsById).some(node => node.type === "image" && !node.props.assetId) && <><h3>Images already placed</h3><div className="asset-icon-grid">{Object.values(store.elementsById).filter(node => node.type === "image" && !node.props.assetId && (node.label || "Image").toLowerCase().includes(query.toLowerCase())).map(node => <button key={node.id} onClick={() => store.selectElement(node.id)}><img src={String(node.props.src || "")} alt="" style={{ width: 48, height: 48, objectFit: "contain" }} /><span>{node.label || "Image"}</span></button>)}</div></>}
    <h3>Built-in icons</h3><div className="asset-icon-grid">{Object.entries(ICON_PATHS).filter(([name]) => name.includes(query.toLowerCase())).map(([name, path]) => <button key={name} aria-label={`Insert ${name} icon`} onClick={() => store.addElement({ ...templates.icon, label: `${name} icon`, props: { ...templates.icon.props, icon: name } })}><svg viewBox="0 0 24 24" fill="currentColor" width="20" height="20"><path d={path} /></svg><span>{name}</span></button>)}</div>
    {!entries.length && <p>No uploaded assets match this search. Upload an image or a WOFF font to start your library.</p>}
  </div>;
}
